theme: jekyll-theme-minimal
title: Ben Kiboma (Software Engineer)
description: I im a full stack developer with experience in Javascript, HTML,CSS, Python, Django, Git and Github. Please reach me via email omayioben@gmail.com or
telephone +254719584717 
